name: "ECSStack"
on:
  workflow_dispatch:
jobs:
  deploy-ecs-stack:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest
          cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

      - name: Terraform Init
        id: init
        working-directory: ./dev-ops/terraform/
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        working-directory: ./dev-ops/terraform/
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ./dev-ops/terraform/
        run: terraform plan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        working-directory: ./dev-ops/terraform/
        run: terraform apply -auto-approve